version: '2'

services:

  app:
    image: sdelements/lets-chat
    links:
      - mongo
    ports:
      - 8080:8080
      - 5222:5222

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017